[package]
name = "spiffy-rs"
version = "1.1.0"
authors = ["Kingloo <k1ngloo@hotmail.com>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
